vim_plugin_task "tabular", "git://github.com/godlygeek/tabular.git"
vim_plugin_task "gundo", "git://github.com/sjl/gundo.vim.git"
vim_plugin_task "velocity", "git://github.com/vim-scripts/velocity.vim.git"
vim_plugin_task "ragtag", "git://github.com/tpope/vim-ragtag.git"
vim_plugin_task "peepopen", "git://github.com/mrchrisadams/vim-peepopen.git"
