#!/usr/bin/env bash

set -e

if ! [ -f "$HOME/strap.sh" ]
then
  echo "Please save strap.sh to your home directory and retry this command again"
  open "https://faun-strap.herokuapp.com/strap.sh?text=1"
  exit 1
else
  chmod +x "$HOME/strap.sh"
  bash "$HOME/strap.sh"
fi
